# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h60d24w3_qS-hBLhAEx2XD2aXRD9Vst-
"""

import datetime
import dateutil
import re

def getData():
  entryData = input("Insira a (categoria do hospede): (datas no formato DDMMAAAA(dia da semana abreveada) que ele irá se hospedar separadas por vírgula)")
  RE_dates = '\d{2}\D{3}\d{4}\(\D*\)'
  RE_category = '\D*:'
  category = re.findall(RE_category,entryData)[0][0:-1]
  dates = re.findall(RE_dates,entryData)
  print(category,"\n",dates)

prices_by_hotel = {
    {}
}
getData()

